# Generated by Django 4.1 on 2022-08-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_excel_doc_one_excel_doc_two_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_doc_one',
            name='file_one',
            field=models.FileField(upload_to='saved/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='excel_doc_two',
            name='file_two',
            field=models.FileField(upload_to='saved/%Y/%m/%d/'),
        ),
    ]
